services:
  aesmd:
    image: ghcr.io/hayao0819/sgxsdk-docker-image:noble-latest
    container_name: aesmd
    environment:
      - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm
    command: ["/opt/intel/sgx-aesm-service/aesm/aesm_service"]
    volumes:
      - aesmd-socket:/var/run/aesmd
  
  hellosgx:
    image: ./Dodkerfile
    container_name: hellosgx
    depends_on:
      - aesmd
    volumes:
      - aesmd-socket:/var/run/aesmd

volumes:
  aesmd-socket:
    external: true
